import type {
  Attendee,
  AttendeeSession,
  CalendarItem,
  CheckIn,
  EmailCampaign,
  EventAnnouncement,
  EventDocument,
  EventIssue,
  EventTask,
  OpsEvent,
  QrCodeRecord,
  Registration,
  RegistrationFunnel,
  RoomLayout,
  RoomLayoutVersion,
  Session,
  Speaker,
  SpeakerRequirement,
  VendorAssignment,
} from "./types";

export function buildQrPayload(
  eventId: string,
  attendeeId: string,
  registrationId: string,
): string {
  return `${eventId}|${attendeeId}|${registrationId}`;
}

const allReqs = (flags: Partial<Record<string, boolean>> = {}): SpeakerRequirement[] => {
  const items = [
    { key: "bio", label: "Biography received" },
    { key: "headshot", label: "Headshot received" },
    { key: "title", label: "Session title approved" },
    { key: "presentation", label: "Presentation uploaded" },
    { key: "av", label: "AV requirements confirmed" },
    { key: "arrival", label: "Arrival time confirmed" },
    { key: "travel", label: "Travel details confirmed" },
    { key: "green", label: "Green room assigned" },
    { key: "mic", label: "Microphone assigned" },
    { key: "briefing", label: "Final briefing complete" },
  ];
  return items.map((i) => ({ ...i, done: flags[i.key] ?? false }));
};

export const opsEvents: OpsEvent[] = [
  {
    id: "evt-ops-winter",
    contractId: "22222222-2222-2222-2222-222222222223",
    name: "Northstar Winter Client Dinner",
    customerName: "Northstar Financial Group",
    startAt: "2026-02-14T18:00:00",
    endAt: "2026-02-14T23:00:00",
    venue: "Meridian Club",
    address: "200 N Michigan Ave, Chicago, IL 60601",
    capacity: 90,
    status: "completed",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-mixer",
    contractId: "22222222-2222-2222-2222-222222222220",
    name: "Spring Mixer — Margin Loss Demo",
    customerName: "Prairie Arts Collective",
    startAt: "2026-03-14T18:00:00",
    endAt: "2026-03-14T23:00:00",
    venue: "Prairie Hall",
    address: "500 Locust St, Des Moines, IA 50309",
    capacity: 180,
    status: "completed",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-1",
    contractId: "22222222-2222-2222-2222-222222222224",
    name: "Harborview Summer Showcase",
    customerName: "Harborview Hospitals",
    startAt: "2026-08-22T09:00:00",
    endAt: "2026-08-22T17:00:00",
    venue: "Harborview Atrium",
    address: "400 Pier Ave, Seattle, WA 98101",
    capacity: 240,
    status: "upcoming",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-2",
    contractId: "stub-contract-meridian",
    name: "Meridian Leadership Conference",
    customerName: "Meridian Financial Group",
    startAt: "2026-09-18T08:00:00",
    endAt: "2026-09-19T16:00:00",
    venue: "Grand Lakes Convention Center",
    address: "1200 Lakeshore Dr, Chicago, IL 60601",
    capacity: 450,
    status: "planning",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-3",
    contractId: "22222222-2222-2222-2222-222222222206",
    name: "Riverfront Charity Ball",
    customerName: "Riverfront Civic League",
    startAt: "2026-09-20T18:00:00",
    endAt: "2026-09-20T23:00:00",
    venue: "Riverfront Hall",
    address: "88 River Walk, Milwaukee, WI 53202",
    capacity: 350,
    status: "planning",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-reveal",
    contractId: "22222222-2222-2222-2222-222222222212",
    name: "New Product Reveal Deposit Hold",
    customerName: "Northstar Financial Group",
    startAt: "2026-10-15T10:00:00",
    endAt: "2026-10-15T22:00:00",
    venue: "Lakeshore Pavilion",
    address: "1 Lakeshore Dr, Chicago, IL 60611",
    capacity: 300,
    status: "planning",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
  {
    id: "evt-ops-gala",
    contractId: "22222222-2222-2222-2222-222222222202",
    name: "Year-End Gala",
    customerName: "Northstar Financial Group",
    startAt: "2026-12-12T17:00:00",
    endAt: "2026-12-12T23:30:00",
    venue: "Lakeshore Pavilion",
    address: "1 Lakeshore Dr, Chicago, IL 60611",
    capacity: 450,
    status: "planning",
    projectManager: "Morgan Manager",
    coordinator: "Chris Employee",
  },
];

export const attendees: Attendee[] = [
  {
    id: "att-1",
    fullName: "Alex Attendee",
    email: "attendee@gmail.com",
    organization: "NovaTech Industries",
    userId: "usr-attendee",
  },
  {
    id: "att-2",
    fullName: "Sam Rivera",
    email: "sam.rivera@example-guest.com",
    organization: "Independent",
  },
  {
    id: "att-3",
    fullName: "Jordan Kim",
    email: "j.kim@example-partner.com",
    organization: "Pulse Partners",
  },
  {
    id: "att-4",
    fullName: "Riley Chen",
    email: "r.chen@example-exhibit.com",
    organization: "Exhibit Co",
  },
  {
    id: "att-5",
    fullName: "Taylor Moss",
    email: "t.moss@example-staff.com",
    organization: "MainEvent Staff",
  },
  {
    id: "att-6",
    fullName: "Casey Quinn",
    email: "c.quinn@example-wait.com",
    organization: "GreenLeaf",
  },
  {
    id: "att-7",
    fullName: "Morgan Blake",
    email: "m.blake@example-cancel.com",
    organization: "Canceled LLC",
  },
];

/** Mutable registration list for demo check-in updates */
export const registrations: Registration[] = [
  {
    id: "reg-1",
    eventId: "evt-ops-1",
    attendeeId: "att-1",
    registrationType: "Professional",
    status: "confirmed",
    source: "Email",
    registeredAt: "2026-07-10",
  },
  {
    id: "reg-2",
    eventId: "evt-ops-1",
    attendeeId: "att-2",
    registrationType: "Guest",
    status: "checked_in",
    source: "Website",
    registeredAt: "2026-07-12",
  },
  {
    id: "reg-3",
    eventId: "evt-ops-1",
    attendeeId: "att-3",
    registrationType: "Executive",
    status: "confirmed",
    source: "Referral",
    registeredAt: "2026-07-15",
  },
  {
    id: "reg-4",
    eventId: "evt-ops-1",
    attendeeId: "att-4",
    registrationType: "Exhibitor",
    status: "registered",
    source: "Website",
    registeredAt: "2026-07-18",
  },
  {
    id: "reg-5",
    eventId: "evt-ops-1",
    attendeeId: "att-5",
    registrationType: "Staff",
    status: "confirmed",
    source: "Email",
    registeredAt: "2026-07-01",
  },
  {
    id: "reg-6",
    eventId: "evt-ops-1",
    attendeeId: "att-6",
    registrationType: "Professional",
    status: "waitlisted",
    source: "Social",
    registeredAt: "2026-08-01",
  },
  {
    id: "reg-7",
    eventId: "evt-ops-1",
    attendeeId: "att-7",
    registrationType: "Professional",
    status: "canceled",
    source: "Website",
    registeredAt: "2026-07-20",
  },
  {
    id: "reg-8",
    eventId: "evt-ops-2",
    attendeeId: "att-1",
    registrationType: "Professional",
    status: "invited",
    source: "Email",
    registeredAt: null,
  },
  {
    id: "reg-9",
    eventId: "evt-ops-2",
    attendeeId: "att-3",
    registrationType: "Executive",
    status: "no_show",
    source: "Email",
    registeredAt: "2026-06-01",
  },
];

export const qrCodes: QrCodeRecord[] = [
  {
    id: "qr-1",
    registrationId: "reg-1",
    eventId: "evt-ops-1",
    attendeeId: "att-1",
    status: "active",
    payload: buildQrPayload("evt-ops-1", "att-1", "reg-1"),
    createdAt: "2026-08-01T10:00:00",
    createdBy: "Morgan Manager",
  },
  {
    id: "qr-2",
    registrationId: "reg-2",
    eventId: "evt-ops-1",
    attendeeId: "att-2",
    status: "active",
    payload: buildQrPayload("evt-ops-1", "att-2", "reg-2"),
    createdAt: "2026-08-01T10:05:00",
    createdBy: "Morgan Manager",
  },
  {
    id: "qr-3",
    registrationId: "reg-7",
    eventId: "evt-ops-1",
    attendeeId: "att-7",
    status: "canceled",
    payload: buildQrPayload("evt-ops-1", "att-7", "reg-7"),
    createdAt: "2026-07-21T09:00:00",
    createdBy: "Morgan Manager",
  },
  {
    id: "qr-4",
    registrationId: "reg-3",
    eventId: "evt-ops-1",
    attendeeId: "att-3",
    status: "active",
    payload: buildQrPayload("evt-ops-1", "att-3", "reg-3"),
    createdAt: "2026-08-01T10:10:00",
    createdBy: "Morgan Manager",
  },
];

/** Mutable check-in log */
export const checkIns: CheckIn[] = [
  {
    id: "ci-1",
    registrationId: "reg-2",
    eventId: "evt-ops-1",
    attendeeId: "att-2",
    checkedInAt: "2026-08-22T08:12:00",
    checkedInBy: "Chris Employee",
    method: "qr_scan",
  },
];

export const emailCampaigns: EmailCampaign[] = [
  {
    id: "em-1",
    eventId: "evt-ops-1",
    name: "Launch invitation",
    audienceType: "All invitees",
    emailType: "Invitation",
    status: "simulated_sent",
    scheduledAt: "2026-07-01T09:00:00",
    sentAt: "2026-07-01T09:00:00",
    createdBy: "Morgan Manager",
    lastModified: "2026-07-01",
    recipientCount: 846,
    openCount: 612,
    template: "invite-v2",
    approvalStatus: "approved",
    fromAddress: "events@mainevent.demo",
    toAudience: "All invitees",
    subject: "You're invited: {{event_name}}",
    bodyHtml:
      "<p>Hi {{attendee_name}},</p><p>You are invited to {{event_name}} on {{event_date}} at {{venue_name}}.</p>",
  },
  {
    id: "em-2",
    eventId: "evt-ops-1",
    name: "Registration confirmation",
    audienceType: "Registered",
    emailType: "Registration confirmation",
    status: "simulated_sent",
    scheduledAt: null,
    sentAt: "2026-07-12T14:00:00",
    createdBy: "Morgan Manager",
    lastModified: "2026-07-12",
    recipientCount: 180,
    openCount: 154,
    template: "confirm-v1",
    approvalStatus: "approved",
    fromAddress: "events@mainevent.demo",
    toAudience: "Registered",
    subject: "Registration confirmed — {{event_name}}",
    bodyHtml:
      "<p>Thanks {{attendee_name}} — your registration for {{event_name}} is confirmed.</p>",
  },
  {
    id: "em-3",
    eventId: "evt-ops-1",
    name: "Check-in instructions",
    audienceType: "Confirmed attendees",
    emailType: "Check-in instructions",
    status: "scheduled",
    scheduledAt: "2026-08-20T10:00:00",
    sentAt: null,
    createdBy: "Chris Employee",
    lastModified: "2026-08-04",
    recipientCount: 165,
    openCount: 0,
    template: "checkin-v1",
    approvalStatus: "approved",
    fromAddress: "events@mainevent.demo",
    toAudience: "Confirmed attendees",
    subject: "Check-in for {{event_name}}",
    bodyHtml:
      "<p>{{attendee_name}}, bring your QR pass to check in at {{venue_name}}.</p>",
  },
  {
    id: "em-4",
    eventId: "evt-ops-1",
    name: "Post-event survey",
    audienceType: "Checked-in attendees",
    emailType: "Survey request",
    status: "draft",
    scheduledAt: null,
    sentAt: null,
    createdBy: "Chris Employee",
    lastModified: "2026-08-05",
    recipientCount: 0,
    openCount: 0,
    template: "survey-v1",
    approvalStatus: "pending",
    fromAddress: "events@mainevent.demo",
    toAudience: "Checked-in attendees",
    cc: "",
    bcc: "",
    subject: "How was {{event_name}}?",
    bodyHtml:
      "<p>Thank you for attending {{event_name}}. Please share feedback.</p>",
  },
  {
    id: "em-5",
    eventId: "evt-ops-2",
    name: "Speaker announcement",
    audienceType: "All invitees",
    emailType: "Speaker announcement",
    status: "pending_approval",
    scheduledAt: null,
    sentAt: null,
    createdBy: "Chris Employee",
    lastModified: "2026-08-03",
    recipientCount: 400,
    openCount: 0,
    template: "speaker-v1",
    approvalStatus: "pending",
    fromAddress: "events@mainevent.demo",
    toAudience: "All invitees",
    subject: "Speaker lineup — {{event_name}}",
    bodyHtml: "<p>Meet our speakers for {{event_name}}.</p>",
  },
];

export const speakers: Speaker[] = [
  {
    id: "spk-1",
    eventId: "evt-ops-1",
    name: "Dr. Nina Patel",
    title: "Chief Product Officer",
    organization: "NovaTech Industries",
    bio: "Leads product strategy for enterprise platforms.",
    status: "Ready",
    publicVisible: true,
    privateEmail: "nina.patel@example-novatech.com",
    arrivalTime: "08:00 AM",
    avRequirements: "Wireless lav + confidence monitor",
    materialsStatus: "complete",
    sessionTitle: "Building the next product moment",
    room: "Main Stage",
    speakingAt: "2026-08-22T10:00:00",
    greenRoom: "Green Room A",
    supportContact: "Chris Employee",
    requirements: allReqs({
      bio: true,
      headshot: true,
      title: true,
      presentation: true,
      av: true,
      arrival: true,
      travel: true,
      green: true,
      mic: true,
      briefing: true,
    }),
  },
  {
    id: "spk-2",
    eventId: "evt-ops-1",
    name: "Marcus Hale",
    title: "Design Director",
    organization: "Studio North",
    bio: "Keynote on experiential product storytelling.",
    status: "Materials Pending",
    publicVisible: true,
    privateEmail: "m.hale@example-studionorth.com",
    arrivalTime: "09:30 AM",
    avRequirements: "HDMI laptop feed",
    materialsStatus: "pending",
    sessionTitle: "Design breakout",
    room: "Studio B",
    speakingAt: "2026-08-22T13:00:00",
    supportContact: "Chris Employee",
    requirements: allReqs({
      bio: true,
      headshot: true,
      title: true,
      presentation: false,
      av: false,
      arrival: true,
      travel: true,
      green: false,
      mic: true,
      briefing: false,
    }),
  },
  {
    id: "spk-3",
    eventId: "evt-ops-1",
    name: "Canceled Speaker",
    title: "Advisor",
    organization: "—",
    bio: "",
    status: "Canceled",
    publicVisible: false,
    materialsStatus: "missing",
    requirements: allReqs(),
  },
  {
    id: "spk-4",
    eventId: "evt-ops-2",
    name: "Elena Soto",
    title: "Managing Partner",
    organization: "Meridian Financial Group",
    bio: "Opening remarks for leadership track.",
    status: "AV Review Needed",
    publicVisible: true,
    materialsStatus: "complete",
    sessionTitle: "Leadership opening",
    room: "Ballroom",
    requirements: allReqs({
      bio: true,
      headshot: true,
      title: true,
      presentation: true,
      av: false,
      arrival: true,
      travel: true,
      green: true,
      mic: false,
      briefing: false,
    }),
  },
  {
    id: "spk-winter-1",
    eventId: "evt-ops-winter",
    name: "Jordan Lee",
    title: "Client Host",
    organization: "Northstar Financial Group",
    bio: "Hosts the winter client dinner program.",
    status: "Ready",
    publicVisible: true,
    materialsStatus: "complete",
    sessionTitle: "Welcome toast",
    room: "Meridian Club",
    requirements: allReqs({ bio: true, headshot: true, title: true }),
  },
  {
    id: "spk-mixer-1",
    eventId: "evt-ops-mixer",
    name: "Sam Okoye",
    title: "Community Lead",
    organization: "Prairie Arts Collective",
    bio: "Opens the spring mixer.",
    status: "Ready",
    publicVisible: true,
    materialsStatus: "complete",
    sessionTitle: "Mixer kickoff",
    room: "Prairie Hall",
    requirements: allReqs({ bio: true, title: true }),
  },
  {
    id: "spk-3-ball",
    eventId: "evt-ops-3",
    name: "Riley Chen",
    title: "Gala Chair",
    organization: "Riverfront Civic League",
    bio: "Charity ball program lead.",
    status: "Materials Pending",
    publicVisible: true,
    materialsStatus: "pending",
    sessionTitle: "Awards presentation",
    room: "Riverfront Hall",
    requirements: allReqs({ bio: true, headshot: false }),
  },
  {
    id: "spk-reveal-1",
    eventId: "evt-ops-reveal",
    name: "Pat Morgan",
    title: "Product Marketing",
    organization: "Northstar Financial Group",
    bio: "Product reveal emcee.",
    status: "Ready",
    publicVisible: true,
    materialsStatus: "complete",
    sessionTitle: "Reveal keynote",
    room: "Main Floor",
    requirements: allReqs({ bio: true, av: true }),
  },
  {
    id: "spk-gala-1",
    eventId: "evt-ops-gala",
    name: "Avery Quinn",
    title: "Executive Sponsor",
    organization: "Northstar Financial Group",
    bio: "Year-end gala remarks.",
    status: "Ready",
    publicVisible: true,
    materialsStatus: "complete",
    sessionTitle: "Closing remarks",
    room: "Pavilion",
    requirements: allReqs({ bio: true, headshot: true }),
  },
];

export const sessions: Session[] = [
  {
    id: "ses-1",
    eventId: "evt-ops-1",
    title: "Doors & welcome",
    description: "Badge pickup and networking coffee",
    startAt: "2026-08-22T09:00:00",
    endAt: "2026-08-22T09:45:00",
    room: "Lobby",
    capacity: 220,
    status: "published",
    speakerIds: [],
  },
  {
    id: "ses-2",
    eventId: "evt-ops-1",
    title: "Keynote: Building the next product moment",
    description: "Opening keynote with product vision",
    startAt: "2026-08-22T10:00:00",
    endAt: "2026-08-22T11:00:00",
    room: "Main Stage",
    capacity: 220,
    status: "published",
    speakerIds: ["spk-1"],
  },
  {
    id: "ses-3",
    eventId: "evt-ops-1",
    title: "Design breakout",
    description: "Interactive storytelling workshop",
    startAt: "2026-08-22T13:00:00",
    endAt: "2026-08-22T14:00:00",
    room: "Studio B",
    capacity: 60,
    status: "published",
    speakerIds: ["spk-2"],
  },
  {
    id: "ses-4",
    eventId: "evt-ops-1",
    title: "Product reveal",
    description: "Live demo and Q&A",
    startAt: "2026-08-22T15:00:00",
    endAt: "2026-08-22T16:00:00",
    room: "Main Stage",
    capacity: 220,
    status: "published",
    speakerIds: ["spk-1"],
  },
  {
    id: "ses-winter-1",
    eventId: "evt-ops-winter",
    title: "Reception & dinner",
    description: "Seated dinner with client hosts",
    startAt: "2026-02-14T18:30:00",
    endAt: "2026-02-14T21:00:00",
    room: "Dining Room",
    capacity: 90,
    status: "published",
    speakerIds: ["spk-winter-1"],
  },
  {
    id: "ses-mixer-1",
    eventId: "evt-ops-mixer",
    title: "Networking blocks",
    description: "Open floor mixer",
    startAt: "2026-03-14T18:00:00",
    endAt: "2026-03-14T22:00:00",
    room: "Prairie Hall",
    capacity: 180,
    status: "published",
    speakerIds: ["spk-mixer-1"],
  },
  {
    id: "ses-2-lead",
    eventId: "evt-ops-2",
    title: "Leadership opening",
    description: "Day-one plenary",
    startAt: "2026-09-18T09:00:00",
    endAt: "2026-09-18T10:00:00",
    room: "Ballroom",
    capacity: 400,
    status: "draft",
    speakerIds: ["spk-4"],
  },
  {
    id: "ses-3-ball",
    eventId: "evt-ops-3",
    title: "Awards presentation",
    description: "Charity awards",
    startAt: "2026-09-20T20:00:00",
    endAt: "2026-09-20T21:00:00",
    room: "Riverfront Hall",
    capacity: 350,
    status: "draft",
    speakerIds: ["spk-3-ball"],
  },
  {
    id: "ses-reveal-1",
    eventId: "evt-ops-reveal",
    title: "Product reveal keynote",
    description: "Main stage reveal",
    startAt: "2026-10-15T19:00:00",
    endAt: "2026-10-15T20:30:00",
    room: "Main Floor",
    capacity: 300,
    status: "draft",
    speakerIds: ["spk-reveal-1"],
  },
  {
    id: "ses-gala-1",
    eventId: "evt-ops-gala",
    title: "Gala program",
    description: "Dinner and remarks",
    startAt: "2026-12-12T18:00:00",
    endAt: "2026-12-12T22:00:00",
    room: "Pavilion",
    capacity: 450,
    status: "draft",
    speakerIds: ["spk-gala-1"],
  },
];

/** Mutable personal schedule */
export const attendeeSessions: AttendeeSession[] = [
  { registrationId: "reg-1", sessionId: "ses-2" },
  { registrationId: "reg-1", sessionId: "ses-4" },
];

export const announcements: EventAnnouncement[] = [
  {
    id: "ann-1",
    eventId: "evt-ops-1",
    title: "Load-in entrance change",
    body: "Use Dock 2 after 7:00 AM. Lobby opens at 8:30 AM for attendees.",
    publishedAt: "2026-08-04T12:00:00",
  },
  {
    id: "ann-2",
    eventId: "evt-ops-1",
    title: "Wi-Fi for attendees",
    body: "Network: NovaLaunch-Guest · Password provided at check-in.",
    publishedAt: "2026-08-03T09:00:00",
  },
];

export const eventDocuments: EventDocument[] = [
  {
    id: "doc-1",
    eventId: "evt-ops-1",
    name: "Attendee guide PDF",
    kind: "Guide",
    publicToAttendee: true,
  },
  {
    id: "doc-2",
    eventId: "evt-ops-1",
    name: "Venue map",
    kind: "Map",
    publicToAttendee: true,
  },
  {
    id: "doc-3",
    eventId: "evt-ops-1",
    name: "Internal run-of-show",
    kind: "Internal",
    publicToAttendee: false,
  },
  {
    id: "doc-4",
    eventId: "evt-ops-1",
    name: "Insurance certificate",
    kind: "Compliance",
    publicToAttendee: false,
    awaitingUpload: true,
  },
  {
    id: "doc-winter-1",
    eventId: "evt-ops-winter",
    name: "Dinner seating chart",
    kind: "Guide",
    publicToAttendee: false,
  },
  {
    id: "doc-mixer-1",
    eventId: "evt-ops-mixer",
    name: "Mixer floor plan",
    kind: "Map",
    publicToAttendee: true,
  },
  {
    id: "doc-2-lead",
    eventId: "evt-ops-2",
    name: "Conference agenda PDF",
    kind: "Guide",
    publicToAttendee: true,
  },
  {
    id: "doc-3-ball",
    eventId: "evt-ops-3",
    name: "Ball run-of-show",
    kind: "Internal",
    publicToAttendee: false,
  },
  {
    id: "doc-reveal-1",
    eventId: "evt-ops-reveal",
    name: "Reveal tech rider",
    kind: "Internal",
    publicToAttendee: false,
  },
  {
    id: "doc-gala-1",
    eventId: "evt-ops-gala",
    name: "Gala guest list (draft)",
    kind: "Internal",
    publicToAttendee: false,
  },
];

export const novatechFunnel: RegistrationFunnel = {
  invitationsSent: 846,
  invitationsOpened: 753,
  websiteVisitors: 339,
  registrationVisitors: 125,
  registrations: 180,
  attendance: 94,
};

export const calendarItems: CalendarItem[] = [
  {
    id: "cal-1",
    eventId: "evt-ops-1",
    title: "Vendor load-in",
    startAt: "2026-08-22T07:00:00",
    endAt: "2026-08-22T08:30:00",
    location: "Dock 2",
    assignee: "Chris Employee",
    status: "open",
    category: "vendor",
  },
  {
    id: "cal-2",
    eventId: "evt-ops-1",
    title: "Attendee check-in window",
    startAt: "2026-08-22T08:30:00",
    endAt: "2026-08-22T09:30:00",
    location: "Lobby",
    assignee: "Chris Employee",
    status: "open",
    category: "checkin",
  },
  {
    id: "cal-3",
    eventId: "evt-ops-1",
    title: "Keynote session",
    startAt: "2026-08-22T10:00:00",
    endAt: "2026-08-22T11:00:00",
    location: "Main Stage",
    assignee: "Dr. Nina Patel",
    status: "open",
    category: "session",
  },
  {
    id: "cal-4",
    eventId: "evt-ops-1",
    title: "Confirm catering",
    startAt: "2026-08-05T09:00:00",
    endAt: "2026-08-05T09:30:00",
    location: "Remote",
    assignee: "Chris Employee",
    status: "blocked",
    category: "task",
    notes: "Overdue — blocks Ready gate",
  },
  {
    id: "cal-5",
    eventId: "evt-ops-1",
    title: "Check-in instructions email",
    startAt: "2026-08-20T10:00:00",
    endAt: "2026-08-20T10:15:00",
    location: "System",
    assignee: "Morgan Manager",
    status: "open",
    category: "email",
  },
  {
    id: "cal-6",
    eventId: "evt-ops-1",
    title: "Room setup",
    startAt: "2026-08-22T06:00:00",
    endAt: "2026-08-22T07:00:00",
    location: "Main Hall",
    assignee: "Chris Employee",
    status: "open",
    category: "setup",
  },
  {
    id: "cal-7",
    eventId: "evt-ops-1",
    title: "Strike / teardown",
    startAt: "2026-08-22T16:00:00",
    endAt: "2026-08-22T18:00:00",
    location: "Main Hall",
    assignee: "Chris Employee",
    status: "open",
    category: "teardown",
  },
  {
    id: "cal-8",
    eventId: "evt-ops-1",
    title: "Customer walkthrough",
    startAt: "2026-08-21T15:00:00",
    endAt: "2026-08-21T16:00:00",
    location: "Harbor Innovation Hall",
    assignee: "Morgan Manager",
    status: "open",
    category: "meeting",
  },
];

export const eventTasks: EventTask[] = [
  {
    id: "task-1",
    eventId: "evt-ops-1",
    title: "Print badge stock",
    dueAt: "2026-08-05T17:00:00",
    assignee: "Chris Employee",
    status: "overdue",
    priority: "high",
  },
  {
    id: "task-2",
    eventId: "evt-ops-1",
    title: "Stage mic check",
    dueAt: "2026-08-22T08:00:00",
    assignee: "Chris Employee",
    status: "open",
    priority: "high",
  },
  {
    id: "task-3",
    eventId: "evt-ops-1",
    title: "Upload venue photos",
    dueAt: "2026-08-06T12:00:00",
    assignee: "Chris Employee",
    status: "open",
    priority: "medium",
  },
  {
    id: "task-4",
    eventId: "evt-ops-1",
    title: "Submit draft survey email",
    dueAt: "2026-08-05T16:00:00",
    assignee: "Chris Employee",
    status: "done",
    priority: "medium",
  },
];

export const eventIssues: EventIssue[] = [
  {
    id: "iss-1",
    eventId: "evt-ops-1",
    title: "Dock 2 gate code outdated",
    severity: "high",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-2",
    eventId: "evt-ops-1",
    title: "Speaker HDMI adapter missing",
    severity: "medium",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-winter-1",
    eventId: "evt-ops-winter",
    title: "Coat check capacity short",
    severity: "low",
    status: "resolved",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-mixer-1",
    eventId: "evt-ops-mixer",
    title: "Catering late delivery",
    severity: "medium",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-2-lead",
    eventId: "evt-ops-2",
    title: "Breakout room AV TBD",
    severity: "medium",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-3-ball",
    eventId: "evt-ops-3",
    title: "Floral vendor confirmation pending",
    severity: "low",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-reveal-1",
    eventId: "evt-ops-reveal",
    title: "Stage riser height conflict",
    severity: "high",
    status: "open",
    reportedBy: "Chris Employee",
  },
  {
    id: "iss-gala-1",
    eventId: "evt-ops-gala",
    title: "Valet overflow plan needed",
    severity: "medium",
    status: "open",
    reportedBy: "Chris Employee",
  },
];

export const vendorAssignments: VendorAssignment[] = [
  {
    id: "va-1",
    vendorUserId: "usr-vendor",
    vendorName: "Victor Vendor / ClearStage AV",
    eventId: "evt-ops-1",
    arrivalTime: "07:00 AM",
    loadIn: "Dock 2",
    contact: "Morgan Manager",
    workOrder: "WO-2026-0881 — Stage AV package",
    // Aligned with work seed: BrightStage AV confirm checked-in + BS-YEG-INV-01 cost entry
    invoiceStatus: "Submitted — BS-YEG-INV-01 ($6,800) pending AP",
    completionStatus: "In progress — AV package confirmed on site",
  },
  {
    id: "va-2",
    vendorUserId: "usr-vendor",
    vendorName: "Victor Vendor / ClearStage AV",
    eventId: "evt-ops-2",
    arrivalTime: "06:30 AM",
    loadIn: "Loading bay A",
    contact: "Morgan Manager",
    workOrder: "WO-2026-0912 — Conference breakout AV",
    invoiceStatus: "Draft — not submitted",
    completionStatus: "Scheduled — load-in 2026-09-17",
  },
];

export const roomLayouts: RoomLayout[] = [
  {
    id: "lay-1",
    eventId: "evt-ops-1",
    vendorUserId: "usr-vendor",
    roomName: "Harborview Atrium",
    widthFt: 80,
    heightFt: 50,
    capacity: 240,
    layoutType: "Theater",
    currentVersionId: "layv-2",
  },
  {
    id: "lay-2",
    eventId: "evt-ops-1",
    vendorUserId: "usr-vendor",
    roomName: "Harborview Atrium — Banquet alt",
    widthFt: 80,
    heightFt: 50,
    capacity: 180,
    layoutType: "Banquet",
    currentVersionId: "layv-3",
  },
];

export const roomLayoutVersions: RoomLayoutVersion[] = [
  {
    id: "layv-1",
    layoutId: "lay-1",
    version: 1,
    status: "draft",
    updatedAt: "2026-08-01T10:00:00",
    updatedBy: "Victor Vendor",
    notes: "Initial theater sketch",
    seatingCapacity: 200,
    items: [
      { id: "li-1", type: "stage", label: "Stage", x: 250, y: 20, w: 200, h: 60, rotation: 0 },
      { id: "li-2", type: "screen", label: "Screen", x: 300, y: 5, w: 100, h: 20, rotation: 0 },
      { id: "li-3", type: "entrance", label: "Entrance", x: 20, y: 200, w: 40, h: 30, rotation: 0 },
    ],
  },
  {
    id: "layv-2",
    layoutId: "lay-1",
    version: 2,
    status: "approved",
    updatedAt: "2026-08-03T14:00:00",
    updatedBy: "Morgan Manager",
    notes: "Approved theater layout",
    seatingCapacity: 200,
    items: [
      { id: "li-1", type: "stage", label: "Stage", x: 250, y: 20, w: 200, h: 60, rotation: 0 },
      { id: "li-2", type: "screen", label: "Screen", x: 300, y: 5, w: 100, h: 20, rotation: 0 },
      { id: "li-3", type: "podium", label: "Podium", x: 320, y: 70, w: 40, h: 30, rotation: 0 },
      { id: "li-4", type: "entrance", label: "Entrance", x: 20, y: 200, w: 40, h: 30, rotation: 0 },
      { id: "li-5", type: "exit", label: "Exit", x: 640, y: 200, w: 40, h: 30, rotation: 0 },
      { id: "li-6", type: "av_control", label: "AV", x: 600, y: 40, w: 50, h: 40, rotation: 0 },
      { id: "li-7", type: "registration_desk", label: "Reg desk", x: 40, y: 160, w: 80, h: 30, rotation: 0 },
    ],
  },
  {
    id: "layv-3",
    layoutId: "lay-2",
    version: 1,
    status: "pending_approval",
    updatedAt: "2026-08-04T11:00:00",
    updatedBy: "Victor Vendor",
    notes: "Banquet alternative — seating exceeds capacity warning",
    seatingCapacity: 260,
    items: [
      { id: "lb-1", type: "stage", label: "Stage", x: 250, y: 10, w: 180, h: 50, rotation: 0 },
      { id: "lb-2", type: "round_table", label: "T1", x: 80, y: 100, w: 50, h: 50, rotation: 0 },
      { id: "lb-3", type: "round_table", label: "T2", x: 160, y: 100, w: 50, h: 50, rotation: 0 },
      { id: "lb-4", type: "round_table", label: "T3", x: 240, y: 100, w: 50, h: 50, rotation: 0 },
      { id: "lb-5", type: "round_table", label: "T4", x: 320, y: 100, w: 50, h: 50, rotation: 0 },
      { id: "lb-6", type: "bar", label: "Bar", x: 500, y: 180, w: 80, h: 40, rotation: 0 },
      { id: "lb-7", type: "dance_floor", label: "Dance", x: 200, y: 180, w: 120, h: 80, rotation: 0 },
      { id: "lb-8", type: "entrance", label: "Entrance", x: 10, y: 200, w: 40, h: 30, rotation: 0 },
    ],
  },
];

export const eventSubnavItems = [
  { href: "/events/[id]", label: "Overview" },
  { href: "/events/[id]/features", label: "Features" },
  { href: "/events/[id]/schedule", label: "Schedule" },
  { href: "/events/[id]/tasks", label: "Tasks" },
  { href: "/events/[id]/attendees", label: "Attendees" },
  { href: "/events/[id]/qr", label: "QR Codes" },
  { href: "/events/[id]/emails", label: "Emails" },
  { href: "/events/[id]/speakers", label: "Speakers" },
  { href: "/events/[id]/agenda", label: "Agenda" },
  { href: "/events/[id]/documents", label: "Documents" },
  { href: "/events/[id]/issues", label: "Issues" },
  { href: "/events/[id]/time-expenses", label: "Time & Expenses" },
];

export const emailTemplates = [
  { id: "invite-v2", name: "Invitation", body: "<p>Hi {{attendee_name}},</p><p>You are invited to {{event_name}} on {{event_date}} at {{venue_name}}.</p>" },
  { id: "confirm-v1", name: "Registration confirmation", body: "<p>Thanks {{attendee_name}} — your registration for {{event_name}} is confirmed.</p>" },
  { id: "checkin-v1", name: "Check-in instructions", body: "<p>{{attendee_name}}, bring your QR pass to check in at {{venue_name}}.</p>" },
  { id: "survey-v1", name: "Survey request", body: "<p>Thank you for attending {{event_name}}. Please share feedback.</p>" },
];
