import type {
  AccessAuditEntry,
  AppUser,
  EventHealthItem,
  Permission,
  RoleAssignment,
  RoleDefinition,
} from "./types";
import { DEMO_PASSWORD } from "./demo-accounts";
import { ROLE_PERMISSIONS } from "@/features/access/matrix";
import type { PermissionKey } from "@/features/access/types";

export { DEMO_PASSWORD };

const PERM_META: Record<
  PermissionKey,
  { label: string; module: string; description: string }
> = {
  "users.read": { label: "View users", module: "Users & Roles", description: "List directory and role assignments" },
  "users.manage": { label: "Manage users", module: "Users & Roles", description: "Invite, disable, and update user profiles" },
  "roles.manage": { label: "Manage roles", module: "Users & Roles", description: "Edit role-permission maps" },
  "audit.read": { label: "View audit log", module: "Controls", description: "Read append-only access and approval audit events" },
  "billing.read": { label: "View billing", module: "Billing & A/R", description: "Open invoices, aging, deposits" },
  "billing.write": { label: "Issue / apply billing", module: "Billing & A/R", description: "Create invoices and manage drafts" },
  "billing.void": { label: "Void / reverse billing", module: "Billing & A/R", description: "Controlled void of invoices and payment reversals" },
  "billing.payment": { label: "Record payments", module: "Billing & A/R", description: "Record and apply customer payments" },
  "billing.export": { label: "Export billing", module: "Billing & A/R", description: "Export AR and invoice reports" },
  "compliance.read": { label: "View compliance", module: "GAAP Compliance", description: "Contract position and recognition views" },
  "compliance.recognize": { label: "Recognize revenue", module: "GAAP Compliance", description: "Post recognition when evidence exists" },
  "compliance.modify": { label: "Apply contract mods", module: "GAAP Compliance", description: "Apply approved change-order treatments" },
  "contracts.read": { label: "View contracts", module: "Contracts", description: "Read engagement and contract records" },
  "contracts.write": { label: "Draft / submit contract changes", module: "Contracts", description: "Draft contracts and submit change orders" },
  "contracts.approve_co": { label: "Approve change orders", module: "Contracts", description: "Approve controlled contract modifications" },
  "costs.read": { label: "View costs", module: "Cost & Resources", description: "Read cost entries" },
  "costs.write": { label: "Post costs", module: "Cost & Resources", description: "Create/update cost entries" },
  "costs.classify": { label: "Classify costs", module: "Cost & Resources", description: "Accounting cost classification" },
  "profitability.read": { label: "View profitability", module: "Financial confidential", description: "Margins and event profitability" },
  "analytics.read": { label: "Analytics Center", module: "Analytics", description: "Historical KPIs and ML projections" },
  "ar.read": { label: "View accounts receivable", module: "Financial confidential", description: "Company AR aging and outstanding balances" },
  "recognition.read": { label: "View revenue recognition", module: "Financial confidential", description: "Earned vs unearned status" },
  "dashboards.executive": { label: "Executive dashboards", module: "Dashboards", description: "Portfolio KPIs" },
  "controls.approve": { label: "Control approvals", module: "Controls", description: "Approve gated actions" },
  "approvals.queue": { label: "Approval Queue", module: "Department Manager", description: "Risk-ranked internal approvals" },
  "exceptions.approve_major": { label: "Major exception approval", module: "Executive", description: "Approve write-offs, discounts, overrides above thresholds" },
  "attendee.portal": { label: "Attendee portal", module: "Attendee", description: "Own registration, QR pass, agenda" },
  "events.operate": { label: "Operate events", module: "Event Operations", description: "Event-level planning and registration" },
  "events.assigned_only": { label: "Assigned event ops", module: "Event Operations", description: "Coordinator work on assigned events only" },
  "qr.manage": { label: "Manage QR codes", module: "Event Operations", description: "Generate and invalidate attendee QR codes" },
  "qr.checkin": { label: "QR check-in", module: "Event Operations", description: "Validate codes and check attendees in" },
  "emails.manage": { label: "Manage emails", module: "Event Operations", description: "Approve, schedule, and simulate campaign sends" },
  "emails.draft": { label: "Draft emails", module: "Event Operations", description: "Draft and submit emails for approval" },
  "speakers.manage": { label: "Manage speakers", module: "Event Operations", description: "Add speakers and approve public materials" },
  "speakers.support": { label: "Speaker support", module: "Event Operations", description: "Update operational speaker details" },
  "vendor.portal": { label: "Vendor portal", module: "Vendor", description: "Assigned work, layouts, own invoices" },
  "customer.portal": { label: "Customer portal", module: "Customer", description: "Own events, invoices, approvals" },
  "expenses.submit": { label: "Submit expenses / time", module: "Operations", description: "Enter hours and submit expenses" },
  "expenses.approve": { label: "Approve expenses", module: "Controls", description: "Approve expenses within authority" },
  "ready_for_billing": { label: "Ready for billing", module: "Event Operations", description: "Mark event ready for Accounting to invoice" },
  "reports.export": { label: "Export reports", module: "Reports", description: "Export management and accounting reports" },
};

export const permissions: Permission[] = (
  Object.keys(PERM_META) as PermissionKey[]
).map((key) => ({ key, ...PERM_META[key] }));

export const roles: RoleDefinition[] = [
  { id: "role-admin", key: "system_admin", name: "System Administrator", description: "Manages users and roles — not default accounting transaction authority", permissionKeys: ROLE_PERMISSIONS.system_admin, homePath: "/dashboard" },
  { id: "role-exec", key: "executive", name: "Executive", description: "Broad read access; major exception approvals above thresholds", permissionKeys: ROLE_PERMISSIONS.executive, homePath: "/dashboard" },
  { id: "role-pm", key: "project_manager", name: "Project Manager", description: "Assigned event ops; ready-for-billing — not payment posting", permissionKeys: ROLE_PERMISSIONS.project_manager, homePath: "/dashboard" },
  { id: "role-coord", key: "event_coordinator", name: "Event Coordinator", description: "Assigned operational work — no AR, P&L, or recognition", permissionKeys: ROLE_PERMISSIONS.event_coordinator, homePath: "/dashboard/employee" },
  { id: "role-acct", key: "accounting", name: "Accounting", description: "Invoices, payments, recognition — not self-approval of exceptions", permissionKeys: ROLE_PERMISSIONS.accounting, homePath: "/dashboard/accounting" },
  { id: "role-vendor", key: "vendor", name: "Vendor", description: "Assigned work only — no internal P&L", permissionKeys: ROLE_PERMISSIONS.vendor, homePath: "/vendor" },
  { id: "role-customer", key: "customer", name: "Customer", description: "Own event portal — approvals and invoices only", permissionKeys: ROLE_PERMISSIONS.customer, homePath: "/dashboard/customer" },
  { id: "role-dept", key: "department_manager", name: "Department Manager", description: "Independent approver — not routine data entry", permissionKeys: ROLE_PERMISSIONS.department_manager, homePath: "/dashboard" },
  { id: "role-attendee", key: "attendee", name: "Attendee", description: "Own registration and attendee-facing info only", permissionKeys: ROLE_PERMISSIONS.attendee, homePath: "/attendee" },
];
/** Demo logins â€” password for all: `demo` */
export const users: AppUser[] = [
  {
    id: "usr-exec",
    fullName: "Elena Executive",
    email: "executive@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "executive",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-01-10",
  },
  {
    id: "usr-mgr",
    fullName: "Morgan Manager",
    email: "manager@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "project_manager",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-02-01",
  },
  {
    id: "usr-emp",
    fullName: "Chris Employee",
    email: "employee@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "event_coordinator",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-03-01",
  },
  {
    id: "usr-acct",
    fullName: "Avery Accounting",
    email: "accounting@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "accounting",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-02-12",
  },
  {
    id: "usr-vendor",
    fullName: "Victor Vendor",
    email: "vendor@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "vendor",
    status: "active",
    organization: "ClearStage AV",
    lastLoginAt: null,
    createdAt: "2026-05-20",
  },
  {
    id: "usr-cust",
    fullName: "Casey Customer",
    email: "customer@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "customer",
    status: "active",
    organization: "Delta Consulting",
    lastLoginAt: null,
    createdAt: "2026-04-15",
  },
  {
    id: "usr-dept",
    fullName: "Dana Dept Manager",
    email: "deptmanager@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "department_manager",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-01-20",
  },
  {
    id: "usr-attendee",
    fullName: "Alex Attendee",
    email: "attendee@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "attendee",
    status: "active",
    organization: "NovaTech Industries",
    lastLoginAt: null,
    createdAt: "2026-06-01",
  },
  {
    id: "usr-admin",
    fullName: "Brandon Admin",
    email: "admin@gmail.com",
    demoPassword: DEMO_PASSWORD,
    roleKey: "system_admin",
    status: "active",
    organization: "MainEvent Internal",
    lastLoginAt: null,
    createdAt: "2026-01-05",
  },
];

export const assignments: RoleAssignment[] = users.map((u, i) => ({
  id: `asg-${i + 1}`,
  userId: u.id,
  roleKey: u.roleKey,
  assignedBy: "Brandon Admin",
  assignedAt: u.createdAt,
}));

export const accessAudit: AccessAuditEntry[] = [
  {
    id: "aud-1",
    at: "2026-08-05T08:15:00",
    actor: "Brandon Admin",
    action: "role.assign",
    target: "Morgan Manager",
    detail: "Assigned Project Manager",
  },
  {
    id: "aud-2",
    at: "2026-08-04T11:00:00",
    actor: "System",
    action: "login.demo",
    target: "executive@gmail.com",
    detail: "Demo session â€” role resolved from account",
  },
];

/** Shared event health seed for role dashboards (fake data). */
export const eventHealth: EventHealthItem[] = [
  {
    id: "eh-1",
    name: "Meridian Leadership Conference",
    customer: "Meridian Financial Group",
    eventDate: "2026-09-18",
    score: 94,
    status: "healthy",
    progressPct: 82,
    stage: "Planning Complete",
    checks: [
      { label: "Contract Signed", ok: true },
      { label: "Deposit Received", ok: true },
      { label: "Budget Healthy", ok: true },
      { label: "Vendors Confirmed", ok: true },
      { label: "Menu Approval", ok: false },
      { label: "Insurance Uploaded", ok: true },
      { label: "Tasks 91% Complete", ok: true },
    ],
    whyNot100: ["Customer menu approval missing"],
  },
  {
    id: "eh-2",
    name: "Hope Harbor Charity Gala",
    customer: "Hope Harbor Foundation",
    eventDate: "2026-10-04",
    score: 58,
    status: "at_risk",
    progressPct: 41,
    stage: "Deposit Pending",
    checks: [
      { label: "Contract Signed", ok: true },
      { label: "Deposit Received", ok: false },
      { label: "Budget Healthy", ok: false },
      { label: "Vendors Confirmed", ok: false },
      { label: "Customer Approval", ok: true },
      { label: "Insurance Uploaded", ok: true },
      { label: "Tasks 41% Complete", ok: false },
    ],
    whyNot100: [
      "Missing required deposit â€” cannot mark Ready",
      "Budget exceeded",
      "Lighting vendor not confirmed",
    ],
  },
  {
    id: "eh-3",
    name: "NovaTech Product Launch",
    customer: "NovaTech Industries",
    eventDate: "2026-08-22",
    score: 76,
    status: "attention",
    progressPct: 82,
    stage: "Execution",
    checks: [
      { label: "Contract Signed", ok: true },
      { label: "Deposit Received", ok: true },
      { label: "Budget Healthy", ok: true },
      { label: "Vendors Confirmed", ok: true },
      { label: "Customer Approval", ok: true },
      { label: "Insurance Uploaded", ok: true },
      { label: "Invoice current", ok: false },
    ],
    whyNot100: ["Invoice overdue > 30 days", "Disputed AV charge open"],
  },
  {
    id: "eh-4",
    name: "Midwest Manufacturing Awards",
    customer: "Midwest Manufacturing Alliance",
    eventDate: "2026-11-14",
    score: 71,
    status: "attention",
    progressPct: 35,
    stage: "Customer Approvals",
    checks: [
      { label: "Contract Signed", ok: false },
      { label: "Deposit Received", ok: true },
      { label: "Budget Healthy", ok: true },
      { label: "Vendors Confirmed", ok: false },
      { label: "Customer Approval", ok: false },
      { label: "Insurance Uploaded", ok: true },
      { label: "Tasks 35% Complete", ok: false },
    ],
    whyNot100: [
      "Pending change-order approval",
      "Security vendor unconfirmed",
    ],
  },
];

